# verification_erreur_python